language: java
jdk: oraclejdk7
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
deploy:
  provider: s3
  access_key_id:
  secure: "r9MOq5tW91O+mUtT2UHP68MyJFmpQeFLGcXCjyU3SLkJg/LDtoPpmSM+UUv8tNIy+dfLFVmqKYWm5ROTzVwrHAKSPeTpbOtJKx8q94GYCpEfYuZruBWdGMmaJRxbvsT4lvK2XAFPZwUtvmlnNwAOEPd3+ilFoTCFwtL9D8lDlfObzv3QzrbMzp7PcgzTJrpW9LhVTotZAWaflPFVkluMZ05kxv/RpzHpOzhVezZJMSXJQF2aTLc7usdTrKF56epH6zSynmoVHY0tE5oH7c67dp8WNWVmUAq07QLwRaBDr5GfwUp3ARgJcrjMczNuGVvYXAiOv6nIhiTiOYKBr+lXct8O8weNmO1ZRRjQV5Qw8j/m7SapCaADPoXoV49Q+bVfsjXMSbvWZuD6dedeIU7SQ/0fs3Ieegsn3SJWxGf5iF1jcFOHI8F7H8GGghzT2Xd05Ul5ATYjgkvpkJOI+IukFblOnnB8mlGsvoE6kH4Vs2W1oIFge7mW6HF9KDSk5OLau4NkWv6qqZQVmP6QhQ4g8APt1lA4AqzkKrluqfZp8cCBXt2kuYR3DtrgwKN8pMiUB7kSdW85jyuRnZR/JVQJZCqxT6ojKuuYign5cBZZiqsY6F3Ef8Dkxb+/blfQDITaEWIUp3p9jtwfOjlFk9hOfm98npgwg0zIzPlg8vMuNEw="
  secret_access_key:
  secure: "cXAJAt6ijJQA29kRG0PlX7ybDH0mDLafal+pIsib+OruambW6d5bWnoTKXGOwhIYR49mb3lPfaYxQ3x99sgD8pXxjSW6MqAv62laTpAAkxXjVDDk8aL4/Tq4RaCsqMQ21AOgFk6u4hvzPrWxyOuJXezVfgsIF6fV3pw29UOCgocbwEdgEowJ0PCVN1Y5BULZ7DTmRBzwsH0dpY2fcB692n0K4dCzWIcr+3TpJCFlRVjJ2E/fo7c8qgsNJjWSYLrHgp3EoBeum5AYRXQVJC6SUhbtP3hFuqKVvEaX46HMa1aqDJ4l7EsrgrTeOV+7eHnD/axaxz9flp3/p11mXfMQOa7WXvwsgJ093hrTcDtRFeQpsB0FA906+BPVWNeGKeVDwDwpYlTqVcsSlu97HQMOOZmf2CsWbWITm8dObxhBwQfo6Sw8OcPrUPReBOcjwmOwkLM/RqUBLcwjEjZUqVW5IEYYAFMud5ICygpdzJhu9FIFkjzvEbEgPga8QK/0pO0Rsm271p0NqHzx7kqbtj4x6zxebAcj5z8Lbwt9N4M2+qAlJOU//OsPalre0Pyi51Y86QmdJF0e3gF+RlPgZ9QOzPFdXPY5oFErRTiY1u9FB2zsfHsS0ELQithXlwGLiSswxrkzzWzq7e9VhfW4rSDTtfnbkg9MRdAu5nsEdSWqlUE="
  bucket: oss.forter.com
  local-dir: /home/travis/.m2/repository/com/forter/remove-annotation-testng-listener/
  upload-dir: repository/com/forter/remove-annotation-testng-listener
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
